version: '3.9'

services:
  db:
    image: postgres:15
    container_name: site_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: site_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    container_name: site-redis
    ports:
      - '6379:6379'
  api:
    build: ./apps/api
    container_name: site-api
    ports:
      - '3000:3000'
      - '5555:5555'
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: curl --fail http://localhost:3000/api/v1/status || exit 1
      interval: 10s
      retries: 5

volumes:
  postgres_data:
